apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: YANDEX_CLOUD_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: YANDEX_CLOUD_KEY_ID
             - name: YANDEX_CLOUD_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: YANDEX_CLOUD_SECRET_KEY
             - name: YANDEX_CLOUD_URL
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: YANDEX_CLOUD_URL
             - name: YANDEX_CLOUD_URL_FILES
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: YANDEX_CLOUD_URL_FILES
             - name: MONGO_URI
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: MONGO_URI
             - name: YANDEX_CLOUD_BUCKET_NAME
               valueFrom:
                 secretKeyRef:
                   name: ft-inctagram-upload-files-production-config-secret
                   key: YANDEX_CLOUD_BUCKET_NAME
