apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER
           livenessProbe:
             httpGet:
               path: /api/v1/health
               port: PORT_CONTAINER
             initialDelaySeconds: 30
             periodSeconds: 30

           env:
             - name: TECH_EMAIL_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: ft-backend-notifier-production-config-secret
                   key: TECH_EMAIL_PASSWORD
             - name: RMQ_URLS
               valueFrom:
                 secretKeyRef:
                   name: ft-backend-notifier-production-config-secret
                   key: RMQ_URLS
             - name: FRONTEND_EMAIL_CONFIRMATION_URL
               valueFrom:
                 secretKeyRef:
                   name: ft-backend-notifier-production-config-secret
                   key: FRONTEND_EMAIL_CONFIRMATION_URL
             - name: FRONTEND_EMAIL_CONFIRMATION_PASSWORD_RECOVERY_URL
               valueFrom:
                 secretKeyRef:
                   name: ft-backend-notifier-production-config-secret
                   key: FRONTEND_EMAIL_CONFIRMATION_PASSWORD_RECOVERY_URL
             - name: TECH_EMAIL
               valueFrom:
                 secretKeyRef:
                   name: ft-backend-notifier-production-config-secret
                   key: TECH_EMAIL
