name: Main Gateway Test & Lint

on:
  push:
    paths:
      - apps/gateway/**
      - .github/workflows/**
    branches-ignore:
      - release/**

jobs:
  tests-unit:
    name: Unit Tests
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Install sharp
        run: yarn add sharp --ignore-engines

      - name: Generate Prisma
        run: yarn prisma generate

      - name: Test
        run: yarn test:gateway

  tests-e2e:
    name: E2E Tests
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    #    needs: tests-unit
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Install sharp
        run: yarn add sharp --ignore-engines

      - name: Prisma deploy migrations
        run: yarn dotenv -e envs/.gateway.test.env prisma migrate deploy

      - name: Generate Prisma
        run: yarn prisma generate

      - name: Test
        run: yarn test:gateway:e2e

  tsc:
    name: Typescript Check
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma
        run: yarn prisma generate

      - name: TSC
        run: yarn tsc:gateway:check

  lint:
    name: Lint
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    #    needs: tsc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Lint Main
        run: yarn lint:gateway:check
